on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ "v*.*.*" ]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: What is this event?
        run: echo "${{ github.event_name }}"
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Compile project
        run: ./gradlew assemble
      - name: Run checks
        run: ./gradlew check
      - name: Publish snapshot
        if: "github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')"
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
  publish:
    if: "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-20.04
    needs: [tests]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build
        run: ./gradlew build
      - name: Publish non-snapshot version
        run: ./gradlew publish -PallowNonSnapshotRelease
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create Servine distributions
        run: ./gradlew assembleDist
      - uses: actions/upload-artifact@v2
        with:
          name: servine
          path: servine/build/distributions/*
