on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: What is this event?
        run: echo "${{ github.event_name }}"
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distrubution: 'adopt'
      - name: Ensure gradlew script is executable
        run: chmod +x ./gradlew
      - name: Compile project
        run: ./gradlew assemble
      - name: Run checks
        run: ./gradlew check

#  publish-snapshot:
#    runs-on: ubuntu-20.04
#    needs: [ tests ]
#    if: github.event == "push"
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Ensure gradlew script is executable
#        run: chmod +x ./gradlew
#      - name: Publish snapshot
#        run: ./gradlew publish
#        env:
#          GITHUB_ACTOR: ${{ github.actor }}
#          GITHUB_TOKEN: ${{ github.token }}


