on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: What is this event?
        run: echo "${{ github.event_name }}"
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Compile project
        run: ./gradlew assemble
      - name: Run checks
        run: ./gradlew check
      - name: Publish snapshot
        if: "github.event == 'push'"
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}


